'use client';

import React, { useState, useMemo } from 'react';
import Link from 'next/link';
import {
  ArrowLeft,
  Code2,
  Copy,
  Check,
  Download,
  ShieldCheck,
  Sparkles,
  Upload,
  Eye,
  Minimize2,
  Zap
} from 'lucide-react';

export default function SvgOptimizerPage() {
  const [svgInput, setSvgInput] = useState<string>(
    `<svg width="100" height="100" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg" xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape">
  <!-- Generated by Illustrator / Inkscape -->
  <g id="layer1" inkscape:groupmode="layer">
    <circle cx="50" cy="50" r="40" stroke="#78ff73" stroke-width="4" fill="#0B0F17" />
    <path d="M 35 50 L 45 60 L 65 40" stroke="#78ff73" stroke-width="4" stroke-linecap="round" stroke-linejoin="round" fill="none" />
  </g>
</svg>`
  );

  const [removeComments, setRemoveComments] = useState(true);
  const [removeEditorAttrs, setRemoveEditorAttrs] = useState(true);
  const [minify, setMinify] = useState(false);
  const [copiedCode, setCopiedCode] = useState(false);
  const [copiedJsx, setCopiedJsx] = useState(false);

  // SVG Optimization Logic
  const optimizedSvg = useMemo(() => {
    let result = svgInput;

    if (!result.trim()) return '';

    // 1. Remove XML declarations and DOCTYPE
    result = result.replace(/<\?xml[\s\S]*?\?>/gi, '');
    result = result.replace(/<!DOCTYPE[\s\S]*?>/gi, '');

    // 2. Remove comments
    if (removeComments) {
      result = result.replace(/<!--[\s\S]*?-->/g, '');
    }

    // 3. Remove editor namespaces & attributes (Inkscape, Sodipodi, Illustrator)
    if (removeEditorAttrs) {
      result = result.replace(/\s+xmlns:sodipodi="[^"]*"/gi, '');
      result = result.replace(/\s+xmlns:inkscape="[^"]*"/gi, '');
      result = result.replace(/\s+inkscape:[a-z-]+="[^"]*"/gi, '');
      result = result.replace(/\s+sodipodi:[a-z-]+="[^"]*"/gi, '');
      result = result.replace(/\s+i:[a-z-]+="[^"]*"/gi, '');
      result = result.replace(/\s+id="layer[0-9]+"/gi, '');
    }

    // 4. Minify whitespace
    if (minify) {
      result = result
        .replace(/>\s+</g, '><')
        .replace(/\s+/g, ' ')
        .trim();
    }

    return result.trim();
  }, [svgInput, removeComments, removeEditorAttrs, minify]);

  // Handle File Upload
  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (event) => {
      const content = event.target?.result as string;
      if (content) setSvgInput(content);
    };
    reader.readAsText(file);
  };

  // Convert SVG to React JSX
  const convertToJsx = (svg: string) => {
    return svg
      .replace(/stroke-width/g, 'strokeWidth')
      .replace(/stroke-linecap/g, 'strokeLinecap')
      .replace(/stroke-linejoin/g, 'strokeLinejoin')
      .replace(/fill-rule/g, 'fillRule')
      .replace(/clip-rule/g, 'clipRule')
      .replace(/xmlns:xlink/g, 'xmlnsXlink')
      .replace(/class=/g, 'className=');
  };

  const copyToClipboard = async (text: string, isJsx = false) => {
    await navigator.clipboard.writeText(text);
    if (isJsx) {
      setCopiedJsx(true);
      setTimeout(() => setCopiedJsx(false), 2000);
    } else {
      setCopiedCode(true);
      setTimeout(() => setCopiedCode(false), 2000);
    }
  };

  const downloadSvg = () => {
    const blob = new Blob([optimizedSvg], { type: 'image/svg+xml' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'optimized.svg';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  // Size stats
  const originalSize = new Blob([svgInput]).size;
  const optimizedSize = new Blob([optimizedSvg]).size;
  const savingsPercent =
    originalSize > 0
      ? Math.round(((originalSize - optimizedSize) / originalSize) * 100)
      : 0;

  return (
    <main className="min-h-screen bg-[#0B0F17] text-slate-100 flex flex-col font-sans">
      {/* Header */}
      <header className="border-b border-slate-800/80 bg-[#0B0F17]/80 backdrop-blur-md sticky top-0 z-50 px-6 py-3 flex items-center justify-between shrink-0">
        <div className="flex items-center gap-4">
          <Link
            href="/"
            className="flex items-center gap-2 text-slate-400 hover:text-[#78ff73] transition-colors text-sm font-medium group"
          >
            <ArrowLeft size={18} className="group-hover:-translate-x-1 transition-transform" />
            <span>Network</span>
          </Link>
          <div className="h-4 w-[1px] bg-slate-800" />
          <div className="flex items-center gap-2">
            <span className="font-bold text-white text-base">SVG Visualizer & Optimizer</span>
            <span className="text-[10px] font-bold px-2 py-0.5 rounded-full bg-emerald-500/10 text-emerald-300 border border-emerald-500/30">
              MEDIA CLUSTER
            </span>
          </div>
        </div>
        <div className="flex items-center gap-2 text-xs text-slate-400 bg-slate-900 px-3 py-1.5 rounded-lg border border-slate-800">
          <ShieldCheck size={14} className="text-[#78ff73]" />
          <span>Client-Side Optimizer</span>
        </div>
      </header>

      {/* Main Container */}
      <div className="flex-1 max-w-7xl w-full mx-auto p-6 md:p-8 space-y-6">
        
        {/* Top Controls Bar */}
        <div className="bg-slate-900/40 border border-slate-800/80 p-4 rounded-2xl flex flex-wrap items-center justify-between gap-4">
          
          {/* Optimization Options */}
          <div className="flex flex-wrap items-center gap-4 text-xs font-medium">
            <label className="flex items-center gap-2 cursor-pointer text-slate-300 hover:text-white transition-colors">
              <input
                type="checkbox"
                checked={removeComments}
                onChange={(e) => setRemoveComments(e.target.checked)}
                className="rounded border-slate-700 bg-slate-900 text-[#78ff73] focus:ring-0"
              />
              <span>Remove Comments</span>
            </label>

            <label className="flex items-center gap-2 cursor-pointer text-slate-300 hover:text-white transition-colors">
              <input
                type="checkbox"
                checked={removeEditorAttrs}
                onChange={(e) => setRemoveEditorAttrs(e.target.checked)}
                className="rounded border-slate-700 bg-slate-900 text-[#78ff73] focus:ring-0"
              />
              <span>Clean Editor Metadata</span>
            </label>

            <label className="flex items-center gap-2 cursor-pointer text-slate-300 hover:text-white transition-colors">
              <input
                type="checkbox"
                checked={minify}
                onChange={(e) => setMinify(e.target.checked)}
                className="rounded border-slate-700 bg-slate-900 text-[#78ff73] focus:ring-0"
              />
              <span>Minify Code</span>
            </label>
          </div>

          {/* Stats Badge */}
          <div className="flex items-center gap-3 text-xs">
            <span className="text-slate-400">
              Size: <strong className="text-white">{originalSize} B</strong> &rarr;{' '}
              <strong className="text-[#78ff73]">{optimizedSize} B</strong>
            </span>
            {savingsPercent > 0 && (
              <span className="px-2 py-0.5 rounded-full bg-[#78ff73]/10 text-[#78ff73] border border-[#78ff73]/20 font-bold">
                -{savingsPercent}%
              </span>
            )}
          </div>

        </div>

        {/* Workspace Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          
          {/* Left Column: Code Editor */}
          <div className="space-y-4 flex flex-col">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2 text-sm font-bold text-white">
                <Code2 size={16} className="text-[#78ff73]" />
                <span>SVG Code Input</span>
              </div>
              
              <label className="flex items-center gap-1.5 text-xs text-slate-400 hover:text-white cursor-pointer bg-slate-900 px-2.5 py-1 rounded-lg border border-slate-800 transition-colors">
                <Upload size={13} />
                <span>Upload .svg</span>
                <input
                  type="file"
                  accept="image/svg+xml"
                  onChange={handleFileUpload}
                  className="hidden"
                />
              </label>
            </div>

            <textarea
              value={svgInput}
              onChange={(e) => setSvgInput(e.target.value)}
              placeholder="Paste raw <svg> code here..."
              className="w-full h-[400px] bg-slate-950/80 border border-slate-800 rounded-2xl p-4 font-mono text-xs text-slate-200 focus:outline-none focus:border-[#78ff73]/50 resize-none transition-colors"
            />
          </div>

          {/* Right Column: Live Visual Preview & Output */}
          <div className="space-y-4 flex flex-col">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2 text-sm font-bold text-white">
                <Eye size={16} className="text-[#78ff73]" />
                <span>Live Preview & Export</span>
              </div>
            </div>

            {/* Visual Preview Canvas */}
            <div className="h-[200px] bg-slate-950/80 border border-slate-800 rounded-2xl p-4 flex items-center justify-center overflow-hidden relative group">
              <div
                className="max-w-full max-h-full flex items-center justify-center [&>svg]:max-w-full [&>svg]:max-h-[160px] [&>svg]:w-auto [&>svg]:h-auto"
                dangerouslySetInnerHTML={{ __html: optimizedSvg }}
              />
            </div>

            {/* Output Actions & JSX Export */}
            <div className="bg-slate-950/60 border border-slate-800 rounded-2xl p-4 space-y-3">
              <div className="flex items-center justify-between text-xs font-bold text-slate-300">
                <span>Optimized Export</span>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-3 gap-2">
                <button
                  onClick={() => copyToClipboard(optimizedSvg)}
                  className="py-2.5 px-3 bg-slate-900 hover:bg-slate-800 text-white border border-slate-800 rounded-xl text-xs font-semibold flex items-center justify-center gap-2 transition-colors"
                >
                  {copiedCode ? <Check size={14} className="text-[#78ff73]" /> : <Copy size={14} />}
                  <span>{copiedCode ? 'Copied!' : 'Copy SVG'}</span>
                </button>

                <button
                  onClick={() => copyToClipboard(convertToJsx(optimizedSvg), true)}
                  className="py-2.5 px-3 bg-slate-900 hover:bg-slate-800 text-white border border-slate-800 rounded-xl text-xs font-semibold flex items-center justify-center gap-2 transition-colors"
                >
                  {copiedJsx ? <Check size={14} className="text-[#78ff73]" /> : <Sparkles size={14} className="text-emerald-400" />}
                  <span>{copiedJsx ? 'Copied!' : 'Copy JSX'}</span>
                </button>

                <button
                  onClick={downloadSvg}
                  className="py-2.5 px-3 bg-[#78ff73] hover:bg-[#68ef63] text-black rounded-xl text-xs font-bold flex items-center justify-center gap-2 transition-colors shadow-lg shadow-[#78ff73]/10"
                >
                  <Download size={14} />
                  <span>Download</span>
                </button>
              </div>
            </div>

          </div>

        </div>

      </div>
    </main>
  );
}